export const REQUESTING = 'REQUESTING_SNAP_INSTALL';

export const SUCCESS = 'SUCCESS_SNAP_INSTALL';

export const FAILURE = 'FAILURE_SNAP_INSTALL';

export const CLEAR = 'CLEAR_SNAP_INSTALL';

export default {
  REQUESTING,
  SUCCESS,
  FAILURE,
  CLEAR,
};
